#!/usr/bin/env python3
import re
import json
import subprocess

import click
import requests


def get_pkg_list(criteria):
    args = [
        'dnf',
        'search',
        criteria
    ]
    p = subprocess.run(args, capture_output=True)

    pkgs = {}

    for full_name in p.stdout.decode().split('\n'):
        if not full_name or full_name.startswith('='):
            continue

        name = full_name.split('.')[0]
        pkgs[name] = True

    return [k for k in pkgs.keys()]


def get_pkg_info(name):
    url = f'https://mdapi.fedoraproject.org/f39/pkg/{name}'

    res = requests.get(url)

    return res.json()


def get_source_url(spec_url):
    res = requests.get(spec_url)

    return re.findall(p, spec_url)


@click.command
@click.option('--criteria', '-c')
@click.option('--output', '-o')
@click.pass_context
def cli(ctx, criteria, output):
    pkgs = get_pkg_list(criteria)
    tmp = {}
    data = {}

    for pkg in pkgs:
        parts = pkg.split('-')
        if len(parts) > 1:
            n = '-'.join(pkg.split('-')[:-1])
        else:
            n = pkg

        tmp[n] = True

    for k in tmp.keys():
        url = f'https://src.fedoraproject.org/rpms/{k}/raw/rawhide/f/{k}.spec'
        res = requests.get(url)
        print(f'{url} - {res.status_code}')
        if res.status_code == 200:
            data[k] = url

        with open(output, 'w+') as f:
            f.write('\n'.join(data.values()))


if __name__ == '__main__':
    cli()
