#!/usr/bin/env python3
import os
import json

import click


def get_spec_list(basedir):
    return [os.path.join(basedir, p) for p in os.listdir(basedir) if p.endswith('.spec')]


def is_cmake_spec(path):
    with open(path, 'r') as f:
        content = f.read()

    return '%cmake' in content


@click.command
@click.option('-j', '--json', 'output_json',  is_flag=True)
def cli(output_json):
    datadir = os.environ.get('AUTOPACK_DATA_DIR', '/opt/autopack/data')
    specdir = f'{datadir}/rpm-specs'
    specs = get_spec_list(specdir)

    if output_json:
        return click.echo(json.dumps({'specs': specs}, indent=2, sort_keys=True))
    
    for spec in specs:
        if is_cmake_spec(spec):
            click.echo(spec)


if __name__ == '__main__':
    cli()
